window.videoStatement = new VideoStatement({
    /*"user":{
        schemeCode: "0001",
        category: "0001",
        memberName: "Alex",
        employer: "Sky",
        beneficiaries: false,
        balance: 15111,
        benefitStatementUrl: ""
    },
    "data":{
            startDate: "05/04/2019",
            startBalance: 0,
            transfers: 0,
            withdrawals: 0,
            employeeContributions: 0,
            employerContributions: 0,
            investmentReturn: 0,
            charges: 0,
            endBalance: 0,
            endDate: "05/04/2020"
    },*/
    "dataTable": "",
    "currency": "",
    "currencySymbol": undefined,
    "currencyName": undefined,
    //TODO "decimalPlaces": 0,
    "id": "",
    "title": "",
    "wrap": "",
    "autoplay": false,
    "pauseOnBlur": undefined,
    "dim": undefined,
    "dimInPoint": undefined,
    "dimOutPoint": undefined,
    "dimDuration": undefined,
    "debug": false,
    "matomo": {
        "trackerName": "",
    },
    "pixi": {
        //"width": 0,
        //"height": 0,
        //"scale": 40,
        //"margin": 0.1,
        "backgroundColor": "#eeeeee",
        "fontFamily": ["Sky Text", "Helvetica", "Arial", "sans-serif !default;"],
        "fontSize": 0,
        "fill": ['#f57815', '#cc3300', '#a02084', '#5b287e', '#234ea7'],
        "fillGradientStops": [0, 0.25, 0.50, 0.75, 1],
        //"fillGradientType": undefined,
        //"webfontSizeCheck": "<6000",
        "resources": {
            //"loading": undefined,
            //"play": undefined,
            //"video": "./static/WA8/vbs/video/intro.mp4",
            "logo": "./static/WA8/vbs/img/logo.png",
            "speakerSheet": "./static/WA8/vbs/img/speakerSheet.json",
            "jar": "./static/WA8/vbs/img/jar.png",
            "interactive": "./static/WA8/vbs/img/interactive.png",
            "beneficiaries": "./static/WA8/vbs/img/beneficiaries.png",
            "beneficiariesHand": "./static/WA8/vbs/img/beneficiariesHand.png",
            //"goldCoin": "./static/WA8/vbs/img/coin.png",
            //"purpleCoin": "./static/WA8/vbs/img/purpleCoin.png",
            //"greenCoin": "./static/WA8/vbs/img/greenCoin.png",
        },
        //"loadingSteps": undefined,
        //"loadingWidth": undefined,
        //"loadingRotationTime": undefined
        //"primaryColor": "#711984",
        //"secondaryColor": "#390B43",
    },
    "box2d": {
        "boundary": undefined
    },
    "mouse": {},
    "audio": {
        "music": "./static/WA8/vbs/audio/music.mp3",
        "musicVolume": undefined,
        "musicInTime": undefined,
        "musicOutTime": undefined,
        "speechVolume": undefined,
        "gapi": {
            "k": "\x41\x49\x7A\x61\x53\x79\x44\x41\x65-\x78\x66\x49\x58\x63\x57\x30\x4F\x36\x44_0_\x57\x70\x55\x6D\x33\x46\x33\x52\x58\x6F\x48\x36\x71\x6D\x32\x73",
            "languageCode": undefined,
            "voice": undefined,
            "gender": undefined,
            "speakingRate": undefined,
            "pitch": undefined,
            "volumeGainDb": undefined,
            "effectsProfileId": undefined, //[],
            //"sampleRateHertz": undefined
        },
        "ccOn": true
    },
    "scenes": {
        //"enabled": ["logoStart","intro","tableStart","jarIn","startBalanceIn","transfersIn","withdrawalsOut","eeContsIn","erContsIn","returnIn","returnOut","endBalance","tableEnd","beneficiaries","jarEnd"],
        //"disabled": ["videoStart","chargesOut"],
        //"list": ["logoStart","intro","tableStart","jarIn","startBalanceIn","transfersIn","withdrawalsOut","eeContsIn","erContsIn","returnIn","returnOut","endBalance","tableEnd","beneficiaries","jarEnd"],
        "logoSize": 'auto',
        "logoSubtitle": 'My Sky Rewards',
        "logoSubtitlePosition": 'bottom',
        //"logoScale": [0.8,1.2],
        // "showSpeaker": false,
        //"speakerColor": "",
        //"introColor": "#333333",
        //"tableHeaderBg": "", //(or rgba(100,100,100,0.5) although currently alpha will be ignored)
        //"tableHeaderColor": "",
        //"tableHeaderFont": [],
        //"tableHeaderFontSize": "",
        "tableRowBg": "#ffffff",
        //"tableRowFont": [],
        //"tableRowFontSize": "",
        // TODO "tableFooterColor": "#ffffff", //currently same as header
        //"startBalanceTableString": "Balance as at #startDate#", // #startDate# will be replaced
        //"transfersTableString": "Transfers",
        //"withdrawalsTableString": "Withdrawals",
        //"employeeContributionsTableString": "#possessive# contributions", // #s will be replaced with possesive name if available, failling back to the text inbetween
        //"employerContributionsTableString": "#employerPossessive# contributions", // #s will be replaced with possesive employer name if available, failling back to the text inbetween
        //"investmentReturnTableString": "Investment return",
        //"chargesTableString": "Charges and fees", 
        //"endBalanceTableString": "Balance as at #endDate#", // #endDate# will be replaced
        "jarLabelColor": "#575757",
        //"jarLabelFont": ["Segoe UI","Frutiger","Frutiger Linotype","Dejavu Sans","Helvetica Neue","Tahoma","Verdana","Segoe","sans-serif"],
        //"jarLabelFontSize": "",
        //"jarFigureColor": "",
        //"jarFigureFont": [],
        //"jarFigureFontSize": "",
        //"jarFigureLabelColor": "",
        //"jarFigureLabelFont": [],
        //"jarFigureLabelFontSize": "",
        //"labelJarString": "#possessive# Pension Account",
        //"startBalanceJarString": "Starting balance",
        //"transfersJarString": "Transferred in",
        //"withdrawalsJarString": "Withdrawn",
        //"employeeContributionsJarString": "#possessive# contributions", // #s will be replaced with possesive name if available, failling back to the text inbetween
        //"employerContributionsJarString": "#employerPossessive# contributions", // #s will be replaced with possesive employer name if available, failling back to the text inbetween
        //"investmentReturnJarString": "Investment return",
        //"chargesJarString": "Charges and fees",
        //"showTooltip": false,
        //"tooltipBg": "",
        //"tooltipBgAlpha": 1,
        //"tooltipBorderColor": "",
        //"tooltipBorderWidth": 0,
        "tooltipColor": "#333",
        //"tooltipFont": "",
        //"tooltipFontSize": "",
        // TODO "isInteractive": false,
        // TODO "showInteractive": false,
        //"startBalanceColor": "",
        //"startBalanceImage": "goldCoin",
        //"transfersColor": "#ffb81c",
        //"transfersImage": "purpleCoin",
        //"employeeContsColor": "#c010a0",
        //"employeeContsImage": "greenCoin",
        "taxRelief": false,
        //"employerContsColor": "#009fd2",
        //"investmentReturnColor": "#702082",
        // TODO "showTransfers": 1, // instead of enabling/disabling scenes use flags like this?
        // TODO "showEmployeeConts": 1,
        // TODO "showEmployerConts": 1,
        // TODO "showInvestmentReturn": 1,
        // TODO "showCharges": 1, // does this internally anyway based on if charges scene is enabled
        //"beneficiariesColor": "",
        //"buttonFont": [],
        "buttonFontSize": "",
        "buttonTextColor": "#ffffff",
        //"buttonBgColor": "#f68121",
        // TODO "buttonHoverBgColor": "#f68121",
        "buttonString": "Take me to my full statement",
        "buttonPosition": "bottom"
    }
});